### ISSUE TITLE
Create Configuration plugin [notes]

### ISSUE THREAD

**Issue by GrayofD4** [d4advancedmedia/d4-pizza#1]
Filter??

**Comment by MerrittofD4** [comment]
Probably would be best! Only other option I can think of is a globally declared array listing each option. Either way, we need to make sure that it is easy to update. One thing that I thought was cool about the current setup is that the config.php includes are easily commentented/uncommented via the Wordpress editor, making it something that is in a way editable without FTP.

**Comment by MerrittofD4** [comment]
Also, can you use filters to activate enqueues or will that throw a headers already sent error

**Comment by GrayofD4** [comment]
Done in 33f2347a9799cc0b9ea71787223dd26ebe9f4363
